# -*- coding: utf-8 -*-
"""Array_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17w4spaaoCp74vTURquLyIlSjABnmloA8
"""

#389. Find the Difference
#SOLUTION
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for i in t:
            if(s.count(i)<t.count(i)):
                return i

#260. Single Number III
#SOLUTION
class Solution:
    def singleNumber(self, nums: List[int]) -> List[int]:
        b = []
        a = Counter(nums)
        for i in a:
            if(a[i]==1):
                b.append(i)
        return(b)

#78. Subsets
class Solution:
    def subsets(self, nums: List[int]) -> List[List[int]]:
        output = [[]]
        
        for num in nums:
            output += [curr + [num] for curr in output] 
        return output