# -*- coding: utf-8 -*-
"""string_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iU_nl5Dxkfzp6bdtkeph4KqySofs9F51
"""

# 1662. Check If Two String Arrays are Equivalent
class Solution:
    def checkIfPangram(self, sentence: str) -> bool:
        if(len(set(sentence))==26):
            return True
        else:
            return False

#1832. Check if the Sentence Is Pangram
class Solution:
    def checkIfPangram(self, sentence: str) -> bool:
        if(len(set(sentence))==26):
            return True
        else:
            return False

#1773. Count Items Matching a Rule
class Solution:
    def countMatches(self, items: List[List[str]], ruleKey: str, ruleValue: str) -> int:
        a = {'type':0,'color':1,'name':2}
        return(sum([1 for item in items if item[a[ruleKey]]==ruleValue]))

